### ISSUE TITLE
[epic][python] Prepare the creation of the python package

### ISSUE THREAD

**Issue by sporniket** [sporniket/yices2-built-with-wasi-sdk#23]
In order to not pollute the name `yowasp-yices2`, the package created will be named `meant-to-be-yowasp-yices2`

Looking at [YoWASP/yosys](https://github.com/YoWASP/yosys) repository, there will be : 
* [ ] Create a `pypi` folder with the files allowing to glue yices build with WASI sdk and python
  * [ ] git ignore file, quick readme, toml project descriptor, dummy version number computer script `setup.py`
  * [ ] `meant-to-be-yowasp-yices2` subfolder, with an initialisation script `__init__.py`, holding the creation of the various launcher scripts
  * [ ] complete `setup.py` to infer the version number of the package.

# Acceptance test

In a temporary folder : 
* Clone the project [amaranth-stuff](https://github.com/sporniket/amaranth-stuff)
* patch the project to use the package `meant-to-be-yowasp-yices2` &rArr; **describe the patch**
* launch the test with `python3 -m pdm`
* **THEN** the yices2 build with WASI sdk is used
* **THEN** the test suite passes
